Expand CI
joostrijneveld/django-embed-template pull request #9
Opened 2017-10-02 20:13 UTC by thomwiggers

Test newer Django versions

2017-10-02 20:13 UTC, thomwiggers commented
De pull-request die je wist dat zou komen (~hacktoberfest)

2017-10-03 11:31 UTC, joostrijneveld commented
Could you also update the `README.md` accordingly?

2017-10-03 14:23 UTC, thomwiggers commented
Done.

2017-10-03 14:31 UTC, joostrijneveld requested changes

2017-10-03 14:31 UTC, joostrijneveld commented on testprojects/django111/testproject/settings.py
> +Generated by 'django-admin startproject' using Django 1.10.
Are you sure this is a Django 1.11 project?

2017-10-03 14:31 UTC, joostrijneveld commented on testprojects/django20/testproject/settings.py
> +Generated by 'django-admin startproject' using Django 1.10.
Same thing as above; is this actually 2.0?

2017-10-03 14:52 UTC, thomwiggers commented on testprojects/django111/testproject/settings.py
> +Generated by 'django-admin startproject' using Django 1.10.
Well, no, it's been copied from 1.10. I don't think that much has changed, actually.

2017-10-03 14:52 UTC, thomwiggers commented on testprojects/django20/testproject/settings.py
> +Generated by 'django-admin startproject' using Django 1.10.
same.

2017-10-17 14:25 UTC, thomwiggers commented
Not sure why Github isn't updating, but I've updated the testprojects to be generated by the respective Django versions.

2017-10-17 14:33 UTC, joostrijneveld approved these changes

2017-10-17 14:35 UTC, joostrijneveld commented
That's weird. When I look at the contents of the branch, your edit does show up. Probably [some cache](https://xkcd.com/908/) somewhere?

2017-10-17 14:35 UTC, merged

2017-10-17 15:01 UTC, thomwiggers commented
They didn't make it into the actual merge afaict though. PR #11 has a diff!